# Generated by Django 6.0.1 on 2026-05-22 21:12

import django.db.models.deletion
import django.utils.timezone
import phac_aspc.django.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CitationDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DemoTaskRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_result_id",
                    phac_aspc.django.fields.CharField(
                        max_length=64, unique=True
                    ),
                ),
                (
                    "kind",
                    phac_aspc.django.fields.CharField(
                        default="sync", max_length=20
                    ),
                ),
                ("label", phac_aspc.django.fields.CharField(max_length=200)),
                ("record_count", models.PositiveIntegerField()),
                ("attempt", models.PositiveIntegerField(default=1)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-completed_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="L1ScreeningQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", phac_aspc.django.fields.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="L2ScreeningQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", phac_aspc.django.fields.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ParameterQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", phac_aspc.django.fields.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", phac_aspc.django.fields.CharField(max_length=255)),
                ("description", phac_aspc.django.fields.TextField()),
                (
                    "created_at",
                    phac_aspc.django.fields.DateTimeField(auto_now_add=True),
                ),
            ],
            options={
                "verbose_name": "Systematic review",
                "verbose_name_plural": "Systematic reviews",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Citation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", phac_aspc.django.fields.TextField(default="")),
                ("abstract", phac_aspc.django.fields.TextField(default="")),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Data"
                    ),
                ),
                ("order", phac_aspc.django.fields.IntegerField()),
                (
                    "dataset",
                    phac_aspc.django.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.citationdataset",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="CitationDatasetColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", phac_aspc.django.fields.CharField(max_length=255)),
                (
                    "dataset",
                    phac_aspc.django.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.citationdataset",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="citationdataset",
            name="screening_columns",
            field=phac_aspc.django.fields.ManyToManyField(
                to="my_app.citationdatasetcolumn"
            ),
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    phac_aspc.django.fields.CharField(max_length=100),
                ),
                (
                    "file",
                    phac_aspc.django.fields.FileField(upload_to="documents/"),
                ),
                ("source_url", phac_aspc.django.fields.URLField(null=True)),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Upload date"
                    ),
                ),
                (
                    "uploaded_by",
                    phac_aspc.django.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DocumentMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "document",
                    phac_aspc.django.fields.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="L1ScreeningQuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option_text",
                    phac_aspc.django.fields.CharField(max_length=255),
                ),
                ("option_value", phac_aspc.django.fields.TextField()),
                (
                    "question",
                    phac_aspc.django.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.l1screeningquestion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="L2ScreeningQuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option_text",
                    phac_aspc.django.fields.CharField(max_length=255),
                ),
                ("option_value", phac_aspc.django.fields.TextField()),
                (
                    "question",
                    phac_aspc.django.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.l2screeningquestion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ParameterQuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "param_name",
                    phac_aspc.django.fields.CharField(max_length=255),
                ),
                ("param_description", phac_aspc.django.fields.TextField()),
                (
                    "question",
                    phac_aspc.django.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.parameterquestion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="parameterquestion",
            name="review",
            field=phac_aspc.django.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="my_app.review"
            ),
        ),
        migrations.AddField(
            model_name="l2screeningquestion",
            name="review",
            field=phac_aspc.django.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="my_app.review"
            ),
        ),
        migrations.AddField(
            model_name="l1screeningquestion",
            name="review",
            field=phac_aspc.django.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="my_app.review"
            ),
        ),
        migrations.AddField(
            model_name="citationdataset",
            name="review",
            field=phac_aspc.django.fields.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="my_app.review"
            ),
        ),
        migrations.CreateModel(
            name="ReviewHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "system_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "business_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("title", phac_aspc.django.fields.CharField(max_length=255)),
                ("description", phac_aspc.django.fields.TextField()),
                ("created_at", phac_aspc.django.fields.DateTimeField()),
                (
                    "edited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eternal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="my_app.review",
                    ),
                ),
            ],
            options={
                "ordering": ["business_date"],
                "get_latest_by": "business_date",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReviewUserLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review",
                    phac_aspc.django.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.review",
                    ),
                ),
                (
                    "user",
                    phac_aspc.django.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="L1ScreeningResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("abandoned_at", models.DateTimeField(blank=True, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("explanation", models.TextField(blank=True, null=True)),
                (
                    "citation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.citation",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.l1screeningquestion",
                    ),
                ),
                (
                    "selected_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.l1screeningquestionoption",
                    ),
                ),
            ],
            options={
                "unique_together": {("citation", "question")},
            },
        ),
        migrations.CreateModel(
            name="L2ScreeningResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("abandoned_at", models.DateTimeField(blank=True, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("explanation", models.TextField(blank=True, null=True)),
                (
                    "citation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.citation",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.l2screeningquestion",
                    ),
                ),
                (
                    "selected_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.l2screeningquestionoption",
                    ),
                ),
            ],
            options={
                "unique_together": {("citation", "question")},
            },
        ),
        migrations.CreateModel(
            name="ParameterExtractionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("abandoned_at", models.DateTimeField(blank=True, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("explanation", models.TextField(blank=True, null=True)),
                (
                    "citation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.citation",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.parameterquestion",
                    ),
                ),
                (
                    "selected_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.parameterquestionoption",
                    ),
                ),
            ],
            options={
                "unique_together": {("citation", "question")},
            },
        ),
    ]
