# Generated by Django 6.0.1 on 2026-05-04 15:31

import django.db.models.deletion
import django.utils.timezone
import phac_aspc.django.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoTaskRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_result_id",
                    phac_aspc.django.fields.CharField(
                        max_length=64, unique=True
                    ),
                ),
                (
                    "kind",
                    phac_aspc.django.fields.CharField(
                        default="sync", max_length=20
                    ),
                ),
                ("label", phac_aspc.django.fields.CharField(max_length=200)),
                ("record_count", models.PositiveIntegerField()),
                ("attempt", models.PositiveIntegerField(default=1)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-completed_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SystematicReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", phac_aspc.django.fields.CharField(max_length=255)),
                ("description", phac_aspc.django.fields.TextField()),
                (
                    "created_at",
                    phac_aspc.django.fields.DateTimeField(auto_now_add=True),
                ),
            ],
            options={
                "verbose_name": "Systematic review",
                "verbose_name_plural": "Systematic reviews",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    phac_aspc.django.fields.CharField(max_length=100),
                ),
                (
                    "file",
                    phac_aspc.django.fields.FileField(upload_to="documents/"),
                ),
                ("source_url", phac_aspc.django.fields.URLField(null=True)),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Upload date"
                    ),
                ),
                (
                    "uploaded_by",
                    phac_aspc.django.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DocumentMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "document",
                    phac_aspc.django.fields.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SystematicReviewHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "system_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "business_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("title", phac_aspc.django.fields.CharField(max_length=255)),
                ("description", phac_aspc.django.fields.TextField()),
                ("created_at", phac_aspc.django.fields.DateTimeField()),
                (
                    "edited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eternal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="my_app.systematicreview",
                    ),
                ),
            ],
            options={
                "ordering": ["business_date"],
                "get_latest_by": "business_date",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SystematicReviewUserLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "systematic_review",
                    phac_aspc.django.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.systematicreview",
                    ),
                ),
                (
                    "user",
                    phac_aspc.django.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
