# Generated by Django 6.0.1 on 2026-05-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentmetadata",
            name="metadata",
        ),
        migrations.AddField(
            model_name="documentmetadata",
            name="coordinates",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="documentmetadata",
            name="pages",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="documentmetadata",
            name="raw_xml",
            field=models.TextField(blank=True, verbose_name="Raw XML"),
        ),
    ]
