# Generated by Django 6.0.1 on 2026-04-27 16:28

import phac_aspc.django.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoTaskRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_result_id",
                    phac_aspc.django.fields.CharField(
                        max_length=64, unique=True
                    ),
                ),
                (
                    "kind",
                    phac_aspc.django.fields.CharField(
                        default="sync", max_length=20
                    ),
                ),
                ("label", phac_aspc.django.fields.CharField(max_length=200)),
                ("project_count", models.PositiveIntegerField()),
                ("attempt", models.PositiveIntegerField(default=1)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-completed_at", "-id"],
            },
        ),
    ]
