# Generated by Django 6.0.1 on 2026-05-29 18:31

import django.db.models.deletion
import phac_aspc.django.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0002_remove_documentmetadata_metadata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="citation",
            name="document",
            field=phac_aspc.django.fields.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="my_app.document",
            ),
        ),
    ]
