# Generated by Django 6.0.1 on 2026-05-06 13:49

import django.db.models.deletion
import phac_aspc.django.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0002_citationdataset_citationdatasetcolumn_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParameterQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", phac_aspc.django.fields.TextField()),
                (
                    "review",
                    phac_aspc.django.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.systematicreview",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParameterQuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "param_name",
                    phac_aspc.django.fields.CharField(max_length=255),
                ),
                ("param_description", phac_aspc.django.fields.TextField()),
                (
                    "question",
                    phac_aspc.django.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.parameterquestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScreeningQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "screening_type",
                    models.CharField(
                        choices=[("L1", "L1"), ("L2", "L2")],
                        max_length=2,
                        verbose_name="Screening type",
                    ),
                ),
                ("question_text", phac_aspc.django.fields.TextField()),
                (
                    "review",
                    phac_aspc.django.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.systematicreview",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScreeningQuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option_text",
                    phac_aspc.django.fields.CharField(max_length=255),
                ),
                ("option_value", phac_aspc.django.fields.TextField()),
                (
                    "question",
                    phac_aspc.django.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.screeningquestion",
                    ),
                ),
            ],
        ),
    ]
