# Generated by Django 6.0.1 on 2026-04-28 00:10

import django.db.models.deletion
import phac_aspc.django.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0002_demotaskrun"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    phac_aspc.django.fields.CharField(max_length=100),
                ),
                (
                    "file",
                    phac_aspc.django.fields.FileField(upload_to="documents/"),
                ),
                ("source_url", phac_aspc.django.fields.URLField(null=True)),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Upload date"
                    ),
                ),
                (
                    "uploaded_by",
                    phac_aspc.django.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at", "-id"],
            },
        ),
    ]
