# Generated by Django 6.0.1 on 2026-05-06 20:59

import django.db.models.deletion
import phac_aspc.django.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_parameterquestion_parameterquestionoption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screeningquestionoption',
            name='question',
        ),
        migrations.CreateModel(
            name='L1ScreeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', phac_aspc.django.fields.TextField()),
                ('review', phac_aspc.django.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.systematicreview')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='L1ScreeningQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', phac_aspc.django.fields.CharField(max_length=255)),
                ('option_value', phac_aspc.django.fields.TextField()),
                ('question', phac_aspc.django.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.l1screeningquestion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='L2ScreeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', phac_aspc.django.fields.TextField()),
                ('review', phac_aspc.django.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.systematicreview')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='L2ScreeningQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', phac_aspc.django.fields.CharField(max_length=255)),
                ('option_value', phac_aspc.django.fields.TextField()),
                ('question', phac_aspc.django.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.l2screeningquestion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ScreeningQuestion',
        ),
        migrations.DeleteModel(
            name='ScreeningQuestionOption',
        ),
    ]
