# Generated by Django 6.0.1 on 2026-05-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0003_citation_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="l2screeningresult",
            name="evidence_sentences",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="l2screeningresult",
            name="evidence_tables",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
