# Generated by Django 6.0.1 on 2026-04-28 15:07

import django.db.models.deletion
import phac_aspc.django.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0003_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "document",
                    phac_aspc.django.fields.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.document",
                    ),
                ),
            ],
        ),
    ]
