# Generated by Django 6.0.1 on 2026-05-04 01:53

import django.db.models.deletion
import django.utils.timezone
import phac_aspc.django.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0004_documentmetadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystematicReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", phac_aspc.django.fields.CharField(max_length=255)),
                ("description", phac_aspc.django.fields.TextField()),
                (
                    "created_at",
                    phac_aspc.django.fields.DateTimeField(auto_now_add=True),
                ),
            ],
            options={
                "verbose_name": "Systematic review",
                "verbose_name_plural": "Systematic reviews",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SystematicReviewHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "system_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "business_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("title", phac_aspc.django.fields.CharField(max_length=255)),
                ("description", phac_aspc.django.fields.TextField()),
                ("created_at", phac_aspc.django.fields.DateTimeField()),
                (
                    "edited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eternal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="my_app.systematicreview",
                    ),
                ),
            ],
            options={
                "ordering": ["business_date"],
                "get_latest_by": "business_date",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SystematicReviewUserLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "systematic_review",
                    phac_aspc.django.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.systematicreview",
                    ),
                ),
                (
                    "user",
                    phac_aspc.django.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Systematic review user link",
                "verbose_name_plural": "Systematic review user links",
            },
        ),
    ]
