# Generated by Django 6.0.1 on 2026-06-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0004_l2screeningresult_evidence_sentences_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="document_type",
        ),
        migrations.RemoveField(
            model_name="document",
            name="source_url",
        ),
        migrations.RemoveField(
            model_name="document",
            name="uploaded_by",
        ),
        migrations.AddField(
            model_name="documentmetadata",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
