# Generated by Django 6.0.1 on 2026-05-08 15:43

import django.db.models.deletion
import phac_aspc.django.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_remove_screeningquestionoption_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citationdataset',
            name='systematic_review',
            field=phac_aspc.django.fields.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='my_app.systematicreview'),
        ),
    ]
