# Generated by Django 6.0.1 on 2026-06-09 20:03

import django.core.validators
import django.db.models.deletion
import my_app.models.document
import phac_aspc.django.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0005_remove_document_document_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentFigure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "caption",
                    models.TextField(
                        blank=True, null=True, verbose_name="Caption"
                    ),
                ),
                (
                    "bounding_box",
                    my_app.models.document.BoundingBoxJSONField(
                        blank=True, default=list
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "index",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="Index",
                    ),
                ),
                (
                    "file",
                    phac_aspc.django.fields.FileField(upload_to=""),
                ),
                (
                    "document",
                    phac_aspc.django.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.document",
                    ),
                ),
            ],
            options={
                "ordering": ["document_id", "index", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DocumentTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "caption",
                    models.TextField(
                        blank=True, null=True, verbose_name="Caption"
                    ),
                ),
                (
                    "bounding_box",
                    my_app.models.document.BoundingBoxJSONField(
                        blank=True, default=list
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "index",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="Index",
                    ),
                ),
                (
                    "table_markdown",
                    models.TextField(verbose_name="Table markdown"),
                ),
                (
                    "document",
                    phac_aspc.django.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.document",
                    ),
                ),
            ],
            options={
                "ordering": ["document_id", "index", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FigureExtractionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    phac_aspc.django.fields.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.document",
                    ),
                ),
            ],
        ),
    ]
