# Generated by Django 6.0.1 on 2026-05-08 18:50

import phac_aspc.django.fields
from django.db import migrations, models
from django.db.models import Prefetch


def _move_citation_dataset_cells_to_rows(apps, schema_editor):
    CitationDatasetCell = apps.get_model("my_app", "CitationDatasetCell")
    CitationDatasetColumn = apps.get_model("my_app", "CitationDatasetColumn")
    CitationDatasetRow = apps.get_model("my_app", "CitationDatasetRow")

    rows = CitationDatasetRow.objects.prefetch_related(
        Prefetch(
            "cells",
            queryset=CitationDatasetCell.objects.select_related("column").order_by(
                "id"
            ),
        )
    ).order_by("id")
    for row in rows:
        title = row.title or ""
        abstract = row.abstract or ""
        data = {}

        for cell in row.cells.all():
            column_name = cell.column.name.strip()
            normalized_name = column_name.casefold()

            if normalized_name == "title" and not title:
                title = cell.value
                continue

            if normalized_name == "abstract" and not abstract:
                abstract = cell.value
                continue

            data[column_name] = cell.value

        row.title = title
        row.abstract = abstract
        row.data = data
        row.save(update_fields=["title", "abstract", "data"])

    for column in CitationDatasetColumn.objects.order_by("id"):
        if column.name.strip().casefold() in {"title", "abstract"}:
            column.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0005_alter_citationdataset_systematic_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="citationdatasetrow",
            name="abstract",
            field=phac_aspc.django.fields.TextField(default=""),
        ),
        migrations.AddField(
            model_name="citationdatasetrow",
            name="data",
            field=models.JSONField(blank=True, default=dict, verbose_name="Data"),
        ),
        migrations.AddField(
            model_name="citationdatasetrow",
            name="title",
            field=phac_aspc.django.fields.TextField(default=""),
        ),
        migrations.RunPython(
            _move_citation_dataset_cells_to_rows,
            migrations.RunPython.noop,
        ),
        migrations.DeleteModel(
            name="CitationDatasetCell",
        ),
    ]
