# Generated by Django 6.0.1 on 2026-05-08 21:45

import phac_aspc.django.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_citationdatasetrow_abstract_citationdatasetrow_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citationdataset',
            name='screening_columns',
            field=phac_aspc.django.fields.ManyToManyField(to='my_app.citationdatasetcolumn'),
        ),
    ]
