# Generated by Django 6.0.1 on 2026-05-14 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0007_citationdataset_screening_columns"),
    ]

    operations = [
        migrations.CreateModel(
            name="L1ScreeningResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("abandoned_at", models.DateTimeField(blank=True, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("explanation", models.TextField(blank=True, null=True)),
                (
                    "citation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.citationdatasetrow",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.l1screeningquestion",
                    ),
                ),
                (
                    "selected_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.l1screeningquestionoption",
                    ),
                ),
            ],
            options={
                "unique_together": {("citation", "question")},
            },
        ),
        migrations.CreateModel(
            name="L2ScreeningResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("abandoned_at", models.DateTimeField(blank=True, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("explanation", models.TextField(blank=True, null=True)),
                (
                    "citation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.citationdatasetrow",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.l2screeningquestion",
                    ),
                ),
                (
                    "selected_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.l2screeningquestionoption",
                    ),
                ),
            ],
            options={
                "unique_together": {("citation", "question")},
            },
        ),
        migrations.CreateModel(
            name="ParameterExtractionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("abandoned_at", models.DateTimeField(blank=True, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("explanation", models.TextField(blank=True, null=True)),
                (
                    "citation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.citationdatasetrow",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.parameterquestion",
                    ),
                ),
                (
                    "selected_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.parameterquestionoption",
                    ),
                ),
            ],
            options={
                "unique_together": {("citation", "question")},
            },
        ),
    ]
