# Generated by Django 6.0.1 on 2026-06-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0007_rename_document_metadata_to_text_extraction_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="l2screeningresult",
            name="evidence_figures",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
