# Generated by Django 6.0.1 on 2026-06-18 16:02

import phac_aspc.django.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0008_l2screeningresult_evidence_figures"),
    ]

    operations = [
        migrations.CreateModel(
            name="LanguageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", phac_aspc.django.fields.CharField(max_length=255)),
                ("key", phac_aspc.django.fields.CharField(max_length=255)),
                (
                    "deployment",
                    phac_aspc.django.fields.CharField(max_length=255),
                ),
                (
                    "is_active",
                    phac_aspc.django.fields.BooleanField(default=True),
                ),
                ("order", phac_aspc.django.fields.IntegerField(default=0)),
                (
                    "is_default",
                    phac_aspc.django.fields.BooleanField(default=False),
                ),
                (
                    "has_multimodal",
                    phac_aspc.django.fields.BooleanField(default=False),
                ),
                (
                    "supported_env",
                    phac_aspc.django.fields.CharField(max_length=20),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
