# Generated by Django 6.0.1 on 2026-06-22 15:50

import django.db.models.deletion
from django.db import migrations, models

import phac_aspc.django.fields


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0009_languagemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="l1screeningresult",
            name="language_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="my_app.languagemodel",
            ),
        ),
        migrations.AddField(
            model_name="l2screeningresult",
            name="language_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="my_app.languagemodel",
            ),
        ),
        migrations.AddField(
            model_name="parameterextractionresult",
            name="language_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="my_app.languagemodel",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="language_model",
            field=phac_aspc.django.fields.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="my_app.languagemodel",
            ),
        ),
        migrations.AddField(
            model_name="reviewhistory",
            name="language_model",
            field=phac_aspc.django.fields.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="my_app.languagemodel",
            ),
        ),
    ]
