# Generated by Django 6.0.1 on 2026-06-22 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0010_l1screeningresult_language_model_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="l1screeningresult",
            name="human_notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Human notes"
            ),
        ),
        migrations.AddField(
            model_name="l1screeningresult",
            name="human_selected_answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="my_app.l1screeningquestionoption",
                verbose_name="Human selected answer",
            ),
        ),
        migrations.AddField(
            model_name="l1screeningresult",
            name="human_validated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Human validated by",
            ),
        ),
        migrations.AddField(
            model_name="l1screeningresult",
            name="human_validation_timestamp",
            field=models.DateTimeField(
                default=None,
                null=True,
                verbose_name="Human validation timestamp",
            ),
        ),
        migrations.AddField(
            model_name="l2screeningresult",
            name="human_notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Human notes"
            ),
        ),
        migrations.AddField(
            model_name="l2screeningresult",
            name="human_selected_answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="my_app.l2screeningquestionoption",
                verbose_name="Human selected answer",
            ),
        ),
        migrations.AddField(
            model_name="l2screeningresult",
            name="human_validated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Human validated by",
            ),
        ),
        migrations.AddField(
            model_name="l2screeningresult",
            name="human_validation_timestamp",
            field=models.DateTimeField(
                default=None,
                null=True,
                verbose_name="Human validation timestamp",
            ),
        ),
    ]
