# Generated by Django 6.0.1 on 2026-06-25

import django.db.models.deletion
from django.db import migrations, models

import phac_aspc.django.fields


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0011_l1screeningresult_human_notes_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ParameterQuestion",
            new_name="ParameterCategory",
        ),
        migrations.RenameModel(
            old_name="ParameterQuestionOption",
            new_name="Parameter",
        ),
        migrations.RenameField(
            model_name="parametercategory",
            old_name="question_text",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="parameter",
            old_name="question",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="parameter",
            old_name="param_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="parameter",
            old_name="param_description",
            new_name="description",
        ),
        migrations.AlterField(
            model_name="parametercategory",
            name="name",
            field=phac_aspc.django.fields.CharField(
                max_length=255, verbose_name="Parameter category name"
            ),
        ),
        migrations.AlterField(
            model_name="parametercategory",
            name="review",
            field=phac_aspc.django.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parameter_categories",
                to="my_app.review",
                verbose_name="Systematic review",
            ),
        ),
        migrations.AlterField(
            model_name="parameter",
            name="category",
            field=phac_aspc.django.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parameters",
                to="my_app.parametercategory",
                verbose_name="Parameter category",
            ),
        ),
        migrations.AlterField(
            model_name="parameter",
            name="description",
            field=phac_aspc.django.fields.TextField(
                verbose_name="Parameter description"
            ),
        ),
        migrations.AlterField(
            model_name="parameter",
            name="name",
            field=phac_aspc.django.fields.CharField(
                max_length=255, verbose_name="Parameter name"
            ),
        ),
        migrations.AlterField(
            model_name="parameterextractionresult",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="my_app.parametercategory",
            ),
        ),
        migrations.AlterField(
            model_name="parameterextractionresult",
            name="selected_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="my_app.parameter",
            ),
        ),
    ]
