# Generated by Django 6.0.1 on 2026-06-26 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0012_rename_parameter_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parameterextractionresult",
            name="selected_option",
        ),
        migrations.AddField(
            model_name="parameterextractionresult",
            name="evidence_figures",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="parameterextractionresult",
            name="evidence_sentences",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="parameterextractionresult",
            name="evidence_tables",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="parameterextractionresult",
            name="found",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="parameterextractionresult",
            name="value",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="parameterextractionresult",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="my_app.parameter",
            ),
        ),
    ]
