# Generated by Codex on 2026-06-29

from django.db import migrations, models

import proj.text


class Migration(migrations.Migration):

    dependencies = [
        (
            "my_app",
            "0013_remove_parameterextractionresult_selected_option_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="parameterextractionresult",
            name="human_found",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name=proj.text.tdt("Human found"),
            ),
        ),
        migrations.AddField(
            model_name="parameterextractionresult",
            name="human_value",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name=proj.text.tdt("Human value"),
            ),
        ),
    ]
