# Generated by Django 6.0.1 on 2026-07-22 21:16

import django.db.models.deletion
import phac_aspc.django.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0014_parameterextractionresult_human_found_and_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentProcessingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("should_run_l2_screening", models.BooleanField(default=False)),
                (
                    "should_run_parameter_extraction",
                    models.BooleanField(default=False),
                ),
                (
                    "citation",
                    phac_aspc.django.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_processing_requests",
                        to="my_app.citation",
                    ),
                ),
            ],
        ),
    ]
