# Generated by Django 6.0.1 on 2026-08-17 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0015_documentprocessingrequest"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DocumentProcessingRequest",
        ),
    ]
