# Generated by Django 6.0.1 on 2026-09-01 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0016_delete_documentprocessingrequest"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DemoTaskRun",
        ),
    ]
