# Generated by Django 6.0.1 on 2026-09-03 19:09

import phac_aspc.django.fields
import versionator.core
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_delete_demotaskrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='users',
            field=phac_aspc.django.fields.ManyToManyField(through='my_app.ReviewUserLink', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewhistory',
            name='users',
            field=versionator.core.M2MTextField(default='[]'),
        ),
    ]
