# Generated by Django 6.0.1 on 2026-09-03 19:36

from django.db import migrations

import phac_aspc.django.fields


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0018_review_users_reviewhistory_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_deleted",
            field=phac_aspc.django.fields.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reviewhistory",
            name="is_deleted",
            field=phac_aspc.django.fields.BooleanField(default=False),
        ),
    ]
