# Generated by Django 6.0.1 on 2026-09-11 23:51

from django.db import migrations


def copy_existing_parameter_answers(apps, schema_editor):
    result_model = apps.get_model("my_app", "ParameterExtractionResult")
    answer_model = apps.get_model("my_app", "ParameterHumanAnswer")

    for result in result_model.objects.exclude(human_found=None):
        answer = answer_model.objects.create(
            citation_id=result.citation_id,
            question_id=result.question_id,
            found=result.human_found,
            value=result.human_value,
        )
        answer_model.objects.filter(pk=answer.pk).update(
            created_at=result.updated_at,
            updated_at=result.updated_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0020_remove_l1screeningresult_human_notes_and_more"),
    ]

    operations = [
        migrations.RunPython(
            copy_existing_parameter_answers,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="parameterextractionresult",
            name="human_found",
        ),
        migrations.RemoveField(
            model_name="parameterextractionresult",
            name="human_value",
        ),
    ]
