# Generated by Django 6.0.1 on 2026-09-14 21:01

import django.db.models.deletion
from django.db import migrations, models

import phac_aspc.django.fields


def copy_parameter_reviews(apps, schema_editor):
    parameter_model = apps.get_model("my_app", "Parameter")
    for parameter in parameter_model.objects.select_related("category"):
        parameter.review_id = parameter.category.review_id
        parameter.save(update_fields=["review"])


class Migration(migrations.Migration):

    dependencies = [
        (
            "my_app",
            "0021_remove_parameterextractionresult_human_found_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="l1screeningquestionoption",
            name="screening_action",
            field=phac_aspc.django.fields.CharField(
                default="screening_disabled", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="l2screeningquestionoption",
            name="screening_action",
            field=phac_aspc.django.fields.CharField(
                default="screening_disabled", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="parameter",
            name="calculation_instructions",
            field=phac_aspc.django.fields.TextField(default=""),
        ),
        migrations.AddField(
            model_name="parameter",
            name="option_type",
            field=phac_aspc.django.fields.CharField(
                default="free_text", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="parameter",
            name="review",
            field=phac_aspc.django.fields.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="my_app.review",
            ),
        ),
        migrations.RunPython(
            copy_parameter_reviews, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="parameter",
            name="review",
            field=phac_aspc.django.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="my_app.review"
            ),
        ),
        migrations.RemoveField(
            model_name="parameter",
            name="category",
        ),
        migrations.AddField(
            model_name="parameter",
            name="units_and_reporting_instructions",
            field=phac_aspc.django.fields.TextField(default=""),
        ),
        migrations.CreateModel(
            name="ParameterOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", phac_aspc.django.fields.CharField(max_length=255)),
                ("context", phac_aspc.django.fields.TextField(default="")),
                (
                    "parameter",
                    phac_aspc.django.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.parameter",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="parameterextractionresult",
            name="selected_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="my_app.parameteroption",
            ),
        ),
        migrations.AddField(
            model_name="parameterhumananswer",
            name="selected_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="my_app.parameteroption",
            ),
        ),
        migrations.DeleteModel(
            name="ParameterCategory",
        ),
    ]
