# Generated by Django 6.0.1 on 2026-09-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0022_parameter_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="l1screeningquestion",
            name="deletion_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="l1screeningquestionoption",
            name="deletion_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="l2screeningquestion",
            name="deletion_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="l2screeningquestionoption",
            name="deletion_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parameter",
            name="deletion_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parameteroption",
            name="deletion_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
