# Generated by Django 6.0.1 on 2026-09-21 17:59

import phac_aspc.django.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0023_l1screeningquestion_deletion_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="disable_filtering",
            field=phac_aspc.django.fields.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reviewhistory",
            name="disable_filtering",
            field=phac_aspc.django.fields.BooleanField(default=False),
        ),
    ]
