# Generated by Django 6.0.1 on 2026-09-22 13:45

from django.db import migrations

import phac_aspc.django.fields


def move_disabled_screening_to_questions(apps, schema_editor):
    database = schema_editor.connection.alias
    for question_name, option_name in (
        ("L1ScreeningQuestion", "L1ScreeningQuestionOption"),
        ("L2ScreeningQuestion", "L2ScreeningQuestionOption"),
    ):
        question_model = apps.get_model("my_app", question_name)
        option_model = apps.get_model("my_app", option_name)
        active_options = option_model.objects.using(database).filter(
            deletion_time__isnull=True
        )
        disabled_question_ids = set(
            active_options.filter(
                screening_action="screening_disabled"
            ).values_list("question_id", flat=True)
        )
        enabled_question_ids = set(
            active_options.exclude(
                screening_action="screening_disabled"
            ).values_list("question_id", flat=True)
        )
        question_model.objects.using(database).filter(
            id__in=disabled_question_ids - enabled_question_ids
        ).update(disable_screening=True)
        option_model.objects.using(database).filter(
            screening_action="screening_disabled"
        ).update(screening_action="screen_in")


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0024_review_disable_filtering_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="l1screeningquestion",
            name="disable_screening",
            field=phac_aspc.django.fields.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="l2screeningquestion",
            name="disable_screening",
            field=phac_aspc.django.fields.BooleanField(default=False),
        ),
        migrations.RunPython(move_disabled_screening_to_questions),
        migrations.AlterField(
            model_name="l1screeningquestionoption",
            name="screening_action",
            field=phac_aspc.django.fields.CharField(
                default="screen_in", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="l2screeningquestionoption",
            name="screening_action",
            field=phac_aspc.django.fields.CharField(
                default="screen_in", max_length=255
            ),
        ),
    ]
