# Generated by Django 6.0.1 on 2026-09-24 20:39

import django.db.models.deletion
from django.db import migrations, models

import phac_aspc.django.fields


def copy_l1_criteria(apps, schema_editor):
    L1Question = apps.get_model("my_app", "L1ScreeningQuestion")
    L1Option = apps.get_model("my_app", "L1ScreeningQuestionOption")
    L2Question = apps.get_model("my_app", "L2ScreeningQuestion")
    L2Option = apps.get_model("my_app", "L2ScreeningQuestionOption")
    database = schema_editor.connection.alias

    for question in L1Question.objects.using(database).all().iterator():
        copy = L2Question.objects.using(database).create(
            l1_question_id=question.pk,
            review_id=question.review_id,
            question_text=question.question_text,
            disable_screening=question.disable_screening,
            deletion_time=question.deletion_time,
        )
        L2Option.objects.using(database).bulk_create(
            [
                L2Option(
                    l1_option_id=option.pk,
                    question_id=copy.pk,
                    option_text=option.option_text,
                    option_value=option.option_value,
                    screening_action=option.screening_action,
                    deletion_time=option.deletion_time,
                )
                for option in L1Option.objects.using(database).filter(
                    question_id=question.pk
                )
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0025_l1screeningquestion_disable_screening_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="l2screeningquestion",
            name="l1_question",
            field=phac_aspc.django.fields.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="my_app.l1screeningquestion",
            ),
        ),
        migrations.AddField(
            model_name="l2screeningquestionoption",
            name="l1_option",
            field=phac_aspc.django.fields.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="my_app.l1screeningquestionoption",
            ),
        ),
        migrations.AddConstraint(
            model_name="l2screeningquestion",
            constraint=models.UniqueConstraint(
                fields=("l1_question",), name="unique_l2_l1_question"
            ),
        ),
        migrations.AddConstraint(
            model_name="l2screeningquestionoption",
            constraint=models.UniqueConstraint(
                fields=("l1_option",), name="unique_l2_l1_option"
            ),
        ),
        migrations.RunPython(copy_l1_criteria, migrations.RunPython.noop),
    ]
