# Generated by Django 6.0.1 on 2026-10-02 17:51

from django.db import migrations

import phac_aspc.django.fields


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0027_l1criticalscreeningresult_l2criticalscreeningresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="l1screeningquestion",
            name="confidence",
            field=phac_aspc.django.fields.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="l2screeningquestion",
            name="confidence",
            field=phac_aspc.django.fields.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="confidence",
            field=phac_aspc.django.fields.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="reviewhistory",
            name="confidence",
            field=phac_aspc.django.fields.FloatField(default=None, null=True),
        ),
    ]
