# Generated by Django 6.0.1 on 2026-08-17 21:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proj", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        blank=True, db_index=True, max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("successful", "Successful"),
                            ("failed", "Failed"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                (
                    "completion_policy",
                    models.CharField(
                        choices=[
                            ("all_success", "All tasks successful"),
                            ("all_settled", "All tasks settled"),
                        ],
                        default="all_success",
                        max_length=20,
                    ),
                ),
                ("members", models.JSONField(default=dict)),
                ("results", models.JSONField(default=dict)),
                ("errors", models.JSONField(default=dict)),
                (
                    "callback_task_path",
                    models.CharField(blank=True, max_length=512),
                ),
                (
                    "callback_task_backend",
                    models.CharField(blank=True, max_length=255),
                ),
                ("callback_kwargs", models.JSONField(default=dict)),
                (
                    "error_callback_task_path",
                    models.CharField(blank=True, max_length=512),
                ),
                (
                    "error_callback_task_backend",
                    models.CharField(blank=True, max_length=255),
                ),
                ("error_callback_kwargs", models.JSONField(default=dict)),
                (
                    "callback_task_result_id",
                    models.CharField(blank=True, max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
